FROM ubuntu:cosmic

RUN apt-get update && \
  apt-get install -y build-essential git libcaffe-cpu-dev libboost-dev libgflags-dev libgoogle-glog-dev libprotobuf-dev liblas-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./pachi /build

WORKDIR /build

RUN make
